### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by Bildcraft1**
added icons + tray icons (i will repack the app for the icons)

### CODE REVIEW

**Comment by MrAlexEsisteGia** [comment]
Please use the official temporary icon
icon

**Comment by Bildcraft1** [comment]
i have do merge nauw

**Comment by Bildcraft1** [comment]
I have changed that so merge

**Comment by Bildcraft1** [comment]
I  have removed the .ico file because electron-packager can package with .png files

**Pull request merged**
